/**
 * Created by CloudRoute on 11-03-2022.
 */

public with sharing class CustomerPortalKYCDocumentWrapper {

    public boolean IsDeleted;
    public String Name;
    public String Account;
    public String DocumentCategory;
    public String Document;
    public String ObjectName;
    public String RecordName;
    public String KYCApprovalStatus;
    public String KYCStatus;
    public String AccountNumber;
    public String attachment;
    public String ExternalId;

}